name = "oref-ingestion"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
HISTORY_PROXY_URL = "https://proxy1.oref-proxy1.workers.dev"

[triggers]
crons = ["3/15 * * * *"]

[observability]
enabled = true

[[r2_buckets]]
binding = "HISTORY_BUCKET"
bucket_name = "oref-history"
