name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-pages:
    concurrency:
      group: pages-prod-main
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PAGES }}
          command: pages deploy web/ --project-name=oref-map
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  deploy-workers:
    concurrency:
      group: worker-${{ matrix.name }}-prod-main
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        name: [proxy1, proxy2, proxy3]
    env:
      ACCOUNT_ID_proxy1: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PROXY1 }}
      ACCOUNT_ID_proxy2: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PROXY2 }}
      ACCOUNT_ID_proxy3: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PROXY3 }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy Worker (${{ matrix.name }})
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env[format('ACCOUNT_ID_{0}', matrix.name)] }}
          wranglerVersion: "4"
          command: deploy --name ${{ matrix.name }}
          workingDirectory: worker

  deploy-ingestion:
    concurrency:
      group: ingestion-prod-main
      cancel-in-progress: true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Deploy ingestion Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PAGES }}
          wranglerVersion: "4"
          command: deploy
          workingDirectory: ingestion